### ISSUE TITLE
image/logo for phone app

### ISSUE THREAD

**Issue by tomasholderness** [smart-facility/cognicity-floodwatch#8]
-  publish to pebble store?

**Comment by matthewberryman** [comment]
I think we should publish once you've fixed #4 #5 #6 and #7

**Comment by tomasholderness** [comment]
Agreed. Hoping to have it published in time for FOSS4G conference end of
August.

Also - @matthewberryman pull request #3 effectively depreciates the cognicity-server floodwatch API endpoint (https://petajakarta.org/banjir/data/api/v2/floodwatch/reports/) so open to suggestions about that.

**Comment by tomasholderness** [comment]
Images & app store resources were added in 2346f9305de7e5d6b62c45664e1247553c0d97ff
